apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: george-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: {{ .Values.istio.gatewaySelector }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "{{ .Values.istio.host }}"
