apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: george-virtualservice
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - "{{ .Values.istio.host }}"
  gateways:
    - george-gateway
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: backend.{{ .Values.namespace }}.svc.cluster.local
            port:
              number: {{ .Values.backend.service.port }}
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: ui.{{ .Values.namespace }}.svc.cluster.local
            port:
              number: {{ .Values.ui.service.port }}
