namespace: george-app

backend:
  replicas: 1
  image: hashicorp/http-echo
  tag: latest
  args:
    - "-text=Hello from backend API"
  service:
    port: 80
    targetPort: 5678

ui:
  replicas: 1
  image: nginx
  tag: latest
  service:
    port: 80

istio:
  host: george.com
  gatewaySelector: ingressgateway
